services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - NODE_ENV=production
      - DB_HOST=postgres_auth
    env_file:
      - .env
    depends_on:
      postgres_auth:
        condition: service_healthy
    networks:
      - auth-network

  postgres_auth:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - NODE_ENV=production
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auth-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:

networks:
  auth-network:
    driver: bridge 